version: '3.4'

services:
  vs-docker:
    image: ${DOCKER_REGISTRY-}vsdocker
    build:
      context: .
      dockerfile: vs-docker/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5201
    ports:
      - "5201:5201"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro